name: ASP.NET
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
env:
  ASPNETCORE_ENVIRONMENT: "Testing"
  DOTNET_ENVIRONMENT: "Testing"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Memory Free
      run: |
        free -m
    - name: Setup couchbase
      run: |
        apt install -y iputils-ping || echo "apt-install failed"
        ping -c 1 couchbase && (
          apt install -y socat
          socat TCP-LISTEN:8091,fork TCP:couchbase:8091 &
          socat TCP-LISTEN:8092,fork TCP:couchbase:8092 &
          socat TCP-LISTEN:8093,fork TCP:couchbase:8093 &
          socat TCP-LISTEN:8094,fork TCP:couchbase:8094 &
          socat TCP-LISTEN:8095,fork TCP:couchbase:8095 &
          socat TCP-LISTEN:8096,fork TCP:couchbase:8096 &
          socat TCP-LISTEN:9140,fork TCP:couchbase:9140 &
          socat TCP-LISTEN:11210,fork TCP:couchbase:11210 &
          socat TCP-LISTEN:11211,fork TCP:couchbase:11211 &
          socat TCP-LISTEN:11207,fork TCP:couchbase:11207 &
          socat TCP-LISTEN:18091,fork TCP:couchbase:18091 &
          socat TCP-LISTEN:18092,fork TCP:couchbase:18092 &
          socat TCP-LISTEN:18093,fork TCP:couchbase:18093 &
          socat TCP-LISTEN:18094,fork TCP:couchbase:18094 &
          socat TCP-LISTEN:18095,fork TCP:couchbase:18095 &
          socat TCP-LISTEN:18096,fork TCP:couchbase:18096 &
        ) && echo "Initialized couchbase port forwarding" || echo "ping couchbase failed, not forwarding ports"
        printf "Waiting for CB startup..."
        wget -O /dev/null  http://localhost:8091/ && echo "DONE" || (echo "FAIL" && panic)

        echo "**Setting up CB Services**"
        curl  -v -X POST http://localhost:8091/node/controller/setupServices -d 'services=kv%2Cn1ql%2Cindex'
        curl  -v -X POST http://localhost:8091/pools/default -d 'memoryQuota=1024' -d 'indexMemoryQuota=512'
        curl  -u Administrator:password -v -X POST http://localhost:8091/settings/web -d 'password=password&username=Administrator&port=SAME'

        echo "**Creating Bucket user_profile**"
         curl -v -X POST http://localhost:8091/pools/default/buckets \
          -u Administrator:password \
          -d name=user_profile \
          -d ramQuotaMB=512 \

        echo "**Creating Collection**" 
        curl  -v -X POST http://localhost:8091/pools/default/buckets/user_profile/scopes/_default/collections \
        -u Administrator:password \
        -d 'name=profile'  

        echo "**Creating Indexes**" 
        curl  -v -X POST http://localhost:8091/settings/indexes \
        -u Administrator:password \
        -d 'storageMode=memory_optimized'

        sleep 5
        curl -v http://localhost:8093/query/service \
        -u Administrator:password \
        -d "statement=CREATE PRIMARY INDEX default_profile_index ON user_profile._default.profile" 

        echo "**Creating CB Server Info**" 
        curl  -u Administrator:password -v -X GET http://localhost:8091/pools/default | jq '.' | grep hostname
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: | 
        cd src/Couchbase.Quickstart  
        dotnet restore
    - name: Build
      run: |
        cd src/Couchbase.Quickstart  
        dotnet build --configuration Debug --no-restore 
    - name: Test
      run: |
        cd src/Couchbase.Quickstart  
        timeout 120 dotnet test --no-build --verbosity normal 
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    services:
      couchbase:
        image: public.ecr.aws/z2f7n8a1/couchbase-da-containers:couchbase-neo 
        options: >-
          --health-cmd "wget -q -O - localhost:8091"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 8095:8095
          - 8096:8096
          - 9140:9140
          - 11210:11210
          - 11211:11211
          - 11207:11207
          - 18091:18091
          - 18092:18092
          - 18093:18093
          - 18094:18094
          - 18095:18095
          - 18096:18096
